server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart_commerce
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jwt:
    signer-key: "fO4/bVM+jFONS8SOvgq/KaZsZ1zauhiNxrpfMPnagasrRMlvIqguiE/0hCcKIDVI0HxulVcEeI3m8hhbZmHZkg=="
    access_token_valid_duration: 120
  mail:
    host: smtp.gmail.com
    port: 587
    username: thephuongop12@gmail.com
    password: qfwe hbib ojxv bnny
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

payment:
  vnpay:
    tmn-code: 03NCHO1Z
    secret-key: WPAPJPIGP1HTS1221UOG81L5QT6HPWE0
    init-payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: http://localhost:5173/checkout-completed
    timeout: 15

pagination:
  product_summaries_size: 10
